# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin user
  admin_email: admin@example.com
  admin_password: password
  domain_name: example.com
  secret_key_base: 8ad504050494659e4cb0fe435ad5e168c3ffd3f9571d038dcc8b04cd2838913b0152dc2183390b77136d5eea6f7fdd7218fb088c4b270efcddc2c6d795a1b2a9

  receptionist_name: receptionist
  receptionist_email: receptionist@example.com
  receptionist_password: password

  doctor_name: doctor1
  doctor_email: doctor1@example.com
  doctor_password: password

  customer_name: customer
  customer_email: customer@example.com
  customer_password: password

test:
  domain_name: example.com
  secret_key_base: 08217cdfe847308600197262ca2872524d0a7ebccc4a8d74bd6eec8ad902a2a18a94dd622c5e3aace144645b2dcef7476c3db94adf3b2a0729ee9db27fb591d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
